services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    develop:
      watch:
        - action: sync
          path: .
          target: /app
          ignore:
            - .venv/
        - action: rebuild
          path: ./uv.lock
    networks:
      - backend

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

networks:
  backend:

volumes:
  caddy_data:
  caddy_config:
