services:
  fastapi:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000
    networks:
      - backend

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    environment:
      DOMAIN: ${DOMAIN:?}
    cap_add:
      - NET_ADMIN
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./caddy:/etc/caddy
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - backend

networks:
  backend:

volumes:
  caddy_data:
  caddy_config:
